apiVersion: apps/v1
kind: Deployment
metadata:
  name: despliegue-exam-1
  labels:
    name: despliegue-exam-1
    app: exam-kube-app
spec:
  replicas: 1
  selector:
    matchLabels:
      name: exam-kube-pod
      app: exam-kube-app
  template:
    metadata:
      name: exam-kube-pod
      labels:
        name: exam-kube-pod
        app: exam-kube-app
    spec:
      containers:
        - name: exam-kube-container
          image: "345554669220.dkr.ecr.us-east-1.amazonaws.com/exam-aws-1:latest"
          imagePullPolicy: Always
          resources:
            limits:
              memory: 512Mi
              cpu: "1"
            requests:
              memory: 128Mi
              cpu: "0.2"
          livenessProbe:
            httpGet:
              path: /revisasivivo
              port: 8080
            initialDelaySeconds: 5
            periodSeconds: 5