apiVersion: v1
kind: Service
metadata:
  name: servicio-app-exam
  labels:
    name: exam-app
    app: exam-kube-app
spec:
  type: NodePort
  selector:
    app: exam-kube-app
  ports:
    - protocol: TCP
      port: 8888
      nodePort: 30027